### ISSUE TITLE
JSON Response for getting info when volume is not present.

### ISSUE THREAD

**Issue by akashshah26595** [openebs/mayaserver#11]
Can we have a JSON response similar to this?
```
{
"error_code":"404"
"message":"volume not found"
}
```
Instead of: **Unexpected response code: 404 (job not found)?**
It will be easy to parse the response from shell script.

**Comment by AmitKumarDas** [comment]
Can you try checking the http status code ?

**Comment by AmitKumarDas** [comment]
I guess http status code worked out for @akashshah26595
