### ISSUE TITLE
Documentation is not complete

### ISSUE THREAD

**Issue by akshat62** [openebs/mayaserver#20]
Add that the Vagrant version should be updated. Vagrantup.com Update README

- [ ]

**Comment by akshat62** [comment]
Update README

**Comment by kmova** [comment]
Thanks @akshat62 for raising this issue. Can you provide the details of the page where the documentation needs to be updated?

Also, if possible, can you please raise an PR with the updated documentation?

**Comment by akshat62** [comment]
vagrant should be updated, Add this. Vagrant version is not working 1.8.1..... Download vagrant 1.9.3 or latest from vagrantup.com and add the commands how to install the zip file. Add these instructions...

**Comment by AmitKumarDas** [comment]
This project's Vagrantfile uses `Vagrant.require_version ">= 1.6.0"`
I guess you are talking about openebs/openebs ?
