### ISSUE TITLE
make init throws the following error

### ISSUE THREAD

**Issue by sivaramdinesh** [openebs/mayaserver#37]
![screenshot from 2017-04-07 06-27-43](https://cloud.githubusercontent.com/assets/25551393/24803462/edd4d3e2-1bc8-11e7-9019-4ba27ad89d4f.png)

**Comment by AmitKumarDas** [comment]
Hi @sivaramdinesh This issue happens when `vagrant up` has not been proper. Please do a `vagrant destroy` & do `vagrant up` again.

The root cause is VM was not able to install go due to network flips.
