### ISSUE TITLE
Show the unit test badge

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/mayaserver#60]
maya api service should display its unit test badge.
It should update the badge results with the latest travis ci run

**Comment by morrme** [comment]
would you like the Travis badge image beside the` godoc` badge in the readme?

**Comment by AmitKumarDas** [comment]
@morrme yes

**Comment by morrme** [comment]
@AmitKumarDas done. https://github.com/openebs/mayaserver/pull/61

**Comment by AmitKumarDas** [comment]
Thanks @morrme .

@prateekpandey14 Lets close this issue once the unit test coverage badge is also in place.

**Comment by morrme** [comment]
@AmitKumarDas where does that badge come from?

**Comment by AmitKumarDas** [comment]
@morrme  Have a look at below references:

https://github.com/asaskevich/govalidator
https://coveralls.io/github/asaskevich/govalidator

**Comment by morrme** [comment]
@AmitKumarDas  ah, you are looking to integrate coveralls. So once you or an admin signs up on the coveralls page, you can then add the config info and get the badge based on the results. 

Here's another one: https://goreportcard.com/report/github.com/openebs/mayaserver

**Comment by AmitKumarDas** [comment]
Thank You @morrme 

Do you mind sending a PR to set up `goreport` for this project ?

**Comment by morrme** [comment]
@AmitKumarDas it looks like goreport does not require any integration, so all that's needed is another badge. I will add it for you.  Do you plan to sign up for coveralls soon as well?

**Comment by AmitKumarDas** [comment]
@morrme Yeah... I do not know anything other than coveralls to get the unit test coverage.

We shall be more than happy if you can suggest anything that is similar or better than coveralls.

**Comment by morrme** [comment]
In addition to Coveralls, there are  CodeClimate and Codecov. I believe all are free for Open Source projects, so it's just a matter of preference.

**Comment by kmova** [comment]
It just tried to signup for coveralls.. looks like it expects us to pay for one private repo, while being free for opensource repo. 

@morrme, I have used codecov for other repository in openebs. Would it make sense to just stick to the same codecov?

**Comment by morrme** [comment]
@kmova If you want coverage for the private repo, they want you to pay, but it should be separate for the open source project. You shouldn't have to do it all together. 
However, if you are already using codecov, then it would be simple just to continue using it for this repo as well. 
I also noticed, your openebs/openebs repo is using badges from openebs/jiva . Is that intentional?

**Comment by kmova** [comment]
yes.. pointing to openebs/jiva was intentional. We moved the storage functionality related builds to openebs/jiva

**Comment by morrme** [comment]
@kmova OK great. 
the badge has been added to this one. Once codecov is enabled, one of us can do the badge and this issue is complete 😃

**Comment by kmova** [comment]
added the codecov badge, with the following commits:

- https://github.com/openebs/mayaserver/commit/7bc090fcedc50d7898d9f367f88d6a5aedd20991
- https://github.com/openebs/mayaserver/commit/50a929dbd66048a395dbcd58357fe294964c2128
- https://github.com/openebs/mayaserver/commit/39190e564155ffe9f76d98d23c0f399022ce3a5c
- https://github.com/openebs/mayaserver/commit/8f99e8403fcd5b1a85c5fc6d395b87aed5a8602d
