### ISSUE TITLE
Enable Golint for mayaserver 

### ISSUE THREAD

**Issue by satyamz** [openebs/mayaserver#63]
I see the score of golint is 50% in [goreport](https://goreportcard.com/report/github.com/openebs/mayaserver#golint). If we do the linting of Go code duly then it'll help us to generate [Go Doc](https://godoc.org/github.com/openebs/mayaserver) properly.
Hence, Mayaserver need to improve go linting.

**Comment by AmitKumarDas** [comment]
The GNUMakefile should take care of installing golint tool. This linting tool is not available by default in a developer's laptop etc.
