### ISSUE TITLE
Issue & Pull Request Template

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/mayaserver#7]
### This is a formal template that collaborators can use to:

- Create a Github issue &
- Later fix that issue as a `Pull Request`

*NOTE - Collaborators should try to use github markdown format as much as possible*

### Issue should have below detail:

- Version / Commit No. of binary where the issue is found
- Deployment scenario of all the services
  - e.g. on laptop, on AWS, on multi-VM, inside docker container, etc
- Detailed explanation of issue
- Screenshots of the issue if possible
  - e.g. log details *in markdown format*

> A contributor may change her role from being one who reports about issue(s) to 
the one who wants to solve the issue herself. She must understand our engineering principles
that will guide her in this role movement:

OpenEBS engineering principles are:
  - *Anybody can contribute to anything*
  - *Done is better than perfect*

### Creating Issue from code marked with `TODO`:

> This code may have lot of `TODO` labels. An interested contributor may raise the TODO in slack
channel & create a Github issue if agreed upon. She may write down the way to implement the TODO
as comments of the above created issue. She can then go ahead and implement the TODO & provide the `Pull Request`.

### Each `Pull Request` (PR) should have below:

- The commit message should refer to Github issue No.
- The commit should implement the `smallest unit` of the targeted issue
  - i.e. *Divide the issue into smaller parts & each part implementation will become a commit*
  - A single commit should not consist of many code changes
  - There can be multiple commits against a PR
- The PR should not implement design level changes on its first attempt
- The design changes can be provided in the next PR with same issue or new enhancement issue
- Detailed explanation of the issue & fix provided in the `git commit` description
- Code comment should be terse but well understood
- Code unit test should cover all scenarios
- Code unit test comment should be terse but well understood
- The variable, struct, interface names can be terse but should be well understood
  - *We prefer well understood name than terse names when naming matters*
- Screenshots of the working fix if possible
  - e.g. log details *in markdown format*

### Further Reads

- [On writing good code](https://chrismm.com/blog/writing-good-code-reduce-the-cognitive-load/?2)
- [Github fork & pull request workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)
- [Better commit message](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message)

**Comment by kmova** [comment]
https://github.com/openebs/openebs/issues/459 will track the inclusion of the content from this issue into the contribution guides. 

Also the pull request and issue templates have been added to the repo: openeba/maya, which will be hosting the code going forward.
